name: openidconnect
description: OpenIdConnect library for flutter.
version: 1.0.32
homepage: https://github.com/4D-Technologies/openidconnect_flutter

environment:
  sdk: '>=3.5.3 <4.0.0'
  flutter: '>=3.24.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  openidconnect_platform_interface: ^1.0.15
  openidconnect_web: ^1.0.23
  # openidconnect_windows: ^0.0.6
  flutter_secure_storage: ^9.2.2
  jwt_decoder: ^2.0.1
  webview_cookie_manager: ^2.0.6

  cryptography: ^2.7.0

  url_launcher: ^6.3.0
  http: ^1.2.2
  retry: ^3.1.2

  # TODO Remove these once native implementations can be added. Refactor so that the native implementations don't need to do the full cycle through.
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        default_package: openidconnect_web
      # windows:
      #   default_package: openidconnect_windows
